FROM archlinux:latest

ARG USERNAME=aigent
ARG USER_UID=1000
ARG USER_GID=985
ARG DOCKER_GID=970

RUN pacman -Sy --noconfirm archlinux-keyring && pacman -Syu --noconfirm \
 && pacman -Sy --noconfirm bash curl wget git ca-certificates unzip zip tar

RUN pacman -Sy --noconfirm base-devel cmake ninja pkgconf \
 && pacman -Sy --noconfirm docker docker-compose

RUN pacman -Sy --noconfirm ripgrep fd fzf tmux neovim which less bat sed sd choose xsv \
 && pacman -Sy --noconfirm entr watchexec parallel just \
 && pacman -Sy --noconfirm jq yq fx hexyl \
 && pacman -Sy --noconfirm tree eza broot zoxide git-delta lazygit

RUN pacman -Sy --noconfirm nodejs-lts-krypton npm yarn pnpm \
 && pacman -Sy --noconfirm shellcheck shfmt prettier eslint \
 && pacman -Sy --noconfirm go delve

RUN pacman -Scc --noconfirm

RUN useradd -u ${USER_UID} -g ${USER_GID} -G ${DOCKER_GID} ${USERNAME} \
 && echo "${USERNAME} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

USER aigent
WORKDIR /home/${USERNAME}

ENV HOME=/home/${USERNAME}
ENV EDITOR=nvim
ENV PATH=$HOME/go/bin:$PATH
ENV GOPATH=$HOME/go
ENV GO111MODULE=on
